[package]
name = "flust-tools"
version = "0.1.0"
authors = ["Flust Contributors"]
edition = "2018"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tracing = "0.1"
tabled = "0.16.0"
supports-hyperlinks = "3.0.0"
flust-build = { path = "../flust-build" }
flust-sdk-api = { path = "../flust-sdk-api" }
