[package]
name = "flust-build"
version = "0.1.0"
edition = "2024"
description = "Flust utilities related to building and linking the Flutter engine."
license = "MIT"

[dependencies]
which = "6.0.2"
dirs = "5.0"
curl = "0.4.46"
indicatif = "0.17.8"
tracing = "0.1"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tempfile = "3.13.0"
xz2 = "0.1.7"
tar = "0.4"
flust-sdk-api = { path = "../flust-sdk-api" }
flate2 = "1.0.35"
