[workspace]
resolver = "2"

members = [
    "flust",
    "flust-engine",
    "flust-engine-api",
    "flust-engine-sys",
    "flust-glutin",
    "flust-plugins",
    "flust-runner-api",
    "flust-sctk",
    "flust-winit",
    #"flutter-tools"
]
