[workspace]
resolver = "2"

members = [
    "flust",
    "flutter-engine",
    "flutter-engine-api",
    "flutter-engine-sys",
    "flust-glutin",
    "flust-plugins",
    "flust-runner-api",
    "flust-sctk",
    "flust-winit",
    #"flutter-glfw",
    #"flutter-tools"
]
