[workspace]
resolver = "2"

members = [
    "flutter-engine",
    "flutter-engine-api",
    "flutter-engine-sys",
    "flutter-glutin",
    "flutter-plugins",
    "flutter-runner",
    "flutter-runner-api",
    "flutter-winit",
    #"flutter-glfw",
    #"flutter-tools"
]
